def test01():
    try:
    print(f"It's working")
    print("An error has occured")
    except Exception as e:
        print("An error has ovccured.\nReasin:{e}")


def test02():
    try:
        
        #all your codes

        print(f"It's working")
    except Exception as e:
        print("An error has occured")